FROM yxlee/social-network-microservices-translate-deps:ubuntu18.04

ARG NUM_CPUS=8

COPY ./ /social-network-microservices
RUN cd /social-network-microservices \
    && mkdir -p build \
    && cd build \
    && cmake .. \
    && make -j${NUM_CPUS} \
    && make install

WORKDIR /social-network-microservices
